### ISSUE TITLE
Visual Editor not working

### ISSUE THREAD

**Issue by bugattie** [storyblok/gatsby-source-storyblok#121]
Hi,
I built a website for a client on Gatsby and I used Storyblok to manage content. After deploying it to Netlify the visual editor is not working saying https://webstarsltd.netlify.app/ refused to connect. I thought maybe Netlify has some issues so I deployed it on Gatsby Cloud but again the same issue https://webstarsfinalmaster.gatsbyjs.io/ refused to connect.
Any workaround for the issue, please?

One thing I notice, For both URLs, if I open up the developer's console I saw an error
You need to provide an access token to interact with Storyblok API.
And a warning
You are not in Draft Mode or in the Visual Editor.

Please help me find the solution.

**Comment by kik-o** [comment]
Try using [https://preview-webstarsfinalmaster.gatsbyjs.io/](https://preview-webstarsfinalmaster.gatsbyjs.io/) after hardcoding the Storyblok API key. If that doesn't work please share your `gatsby-config.js` and any relevant code snippets

P.S. you may want to consider adding a check so that you only load SB bridge when you're in the visual editor for performance sake

**Comment by schabibi1** [comment]
@bugattie Did you provide a public API key token in Netlify? [https://docs.netlify.com/environment-variables/overview/](https://docs.netlify.com/environment-variables/overview/)

It's been a while, so it's not relevant to keep this issue open. But let me know/feel free to re-open this issue if you still face this issue.
