### ISSUE TITLE
Resolve Links is not properly returning

### ISSUE THREAD

**Issue by simonsaysmath** [storyblok/gatsby-source-storyblok#28]
Passing in options for resolveLinks: 'url' in the gatsby-config.js file is not properly returning response for story links as detailed here:

https://www.storyblok.com/cl/url-resolving#request-with--resolvelinksurl

Instead it seems to be treated as resolveLinks: 'story'.

Passing resolve links through the storyblok GraphQL endpoint (http://gapi-browser.storyblok.com/) does resolve the links properly.

**Comment by SimeonC** [comment]
It looks like this has been fixed in the repo but not published to NPM yet.

As a workaround use `"gatsby-source-storyblok": "git@github.com:storyblok/gatsby-source-storyblok.git#b5ac1a38a2e2f4710e9391c2de2a7f43593a07ab",` in package.json.

@onefriendaday Can we get the latest changes published to npm?

**Comment by SimeonC** [comment]
Nice! Thanks for publishing this 😁 

I confirm this is fixed in v1 https://github.com/storyblok/gatsby-source-storyblok/releases/tag/v1.0.0

**Comment by emanuelgsouza** [comment]
Great! So, I'll close this issue
